version: '3'

services:
  app:
    image: items_manager:1.0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always